export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PACIENTE_REPOSITORY = Symbol('PACIENTE_REPOSITORY');
export const AGENDAMENTO_REPOSITORY = Symbol('AGENDAMENTO_REPOSITORY');
export const PRONTUARIO_REPOSITORY = Symbol('PRONTUARIO_REPOSITORY');
export const JWT_SERVICE = Symbol('JWT_SERVICE');
export const VALIDACAO_SERVICE = Symbol('VALIDACAO_SERVICE');
export const CRYPTOGRAPHY_SERVICE = Symbol('CRYPTOGRAPHY_SERVICE');
